language: java
jdk:
  - oraclejdk8
dist: trusty
sudo: required
before_install:
  - mysql -h127.0.0.1 -e "CREATE DATABASE geodatatest CHARACTER SET UTF8mb4 COLLATE utf8mb4_bin; USE mysql;\nUPDATE user SET password=PASSWORD('qwerty123') WHERE user='root';\nFLUSH PRIVILEGES;\n"
addons:
  mariadb: '10.1'