version: '3'
services:
  server:
    image: ethlo/geodata-server:1.0.0-SNAPSHOT
    restart: on-failure
    expose:
      - 6565
    ports:
      - "6566:6565"
    deploy:
      resources:
        limits:
          memory: 2g